### PR TITLE
Force host network for docker containers

### PR DESCRIPTION
**Pull request by zeroem**

### CODE REVIEW

**Comment by zeroem** [comment]
Don't merge this just yet, it looks like --net=host breaks --hostname=foobar

**Comment by jchauncey** [comment]
yeah that would suck

**Comment by zeroem** [comment]
well, my guess is that --net=host implies that the container hostname is the same as the docker host, testing that assumption.

**Comment by zeroem** [comment]
yes, it does appear that --net=host implies that the container hostname matches the docker host's

**Comment by zeroem** [comment]
This solution is a non-start due to docker/docker#5899

sequenceiq/docker-pam does appear to provide a work around, but we'd have to integrate it into Rallysoftware/docker-centos to work.

**Comment by zeroem** [comment]
This is dependent on RallySoftware/docker-centos#5 being merged before the new gem is cut.

**Comment by zeroem** [comment]
This is not a viable solution. In order to use su in a container, we have to disable audit logging for su. Security deemed this unacceptable.

**Pull request closed without merging**
